### ISSUE TITLE
run error on camel 4.2

### ISSUE THREAD

**Issue by huuhoait** [apache/camel-kamelets-examples#48]
hi all!
there was a problem when i built:: 
 jbang camel@apache/camel run *
2023-12-04 21:54:07.790  INFO 2405 --- [           main] org.apache.camel.main.MainSupport   : Apache Camel (JBang) 4.2.0 is starting
2023-12-04 21:54:07.953  INFO 2405 --- [           main] org.apache.camel.main.MainSupport   : Using Java 17.0.9 with PID 2405. Started by hoale in /Volumes/XData/Java/demo2
org.apache.camel.PropertyBindingException: Error binding property (camel.server.metricsEnabled=true) with name: metricsEnabled on bean: org.apache.camel.main.HttpServerConfigurationProperties@6c42f2a1 with value: true
        at org.apache.camel.main.MainHelper.setPropertiesOnTarget(MainHelper.java:352)
        at org.apache.camel.main.BaseMainSupport.setHttpServerProperties(BaseMainSupport.java:1428)
        at org.apache.camel.main.BaseMainSupport.doConfigureCamelContextFromMainConfiguration(BaseMainSupport.java:1094)
        at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:450)
        at org.apache.camel.main.MainSupport.autoconfigure(MainSupport.java:73)
        at org.apache.camel.main.KameletMain.autoconfigure(KameletMain.java:614)
        at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:657)
        at org.apache.camel.main.MainSupport.initCamelContext(MainSupport.java:339)
        at org.apache.camel.main.KameletMain.doInit(KameletMain.java:311)

**Comment by davsclaus** [comment]
You need Camel 4.3.0 when its released

Or try with 4.3.0-SNAPSHOT

**Comment by huuhoait** [comment]
tks
